"""baseline schema

Revision ID: 31054845db94
Revises: 
Create Date: 2026-07-08 01:52:02.766809
"""
from alembic import op
import sqlalchemy as sa


revision = '31054845db94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('qualified_lead_criteria', sa.JSON(), nullable=True),
    sa.Column('branding', sa.JSON(), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('custom_domain_token', sa.String(length=100), nullable=True),
    sa.Column('custom_domain_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_custom_domain'), 'organizations', ['custom_domain'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vertical', sa.String(length=100), nullable=True),
    sa.Column('lead_quality_source', sa.String(length=20), nullable=False),
    sa.Column('metric_settings', sa.JSON(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_vertical'), 'clients', ['vertical'], unique=False)
    op.create_table('email_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('to_address', sa.String(length=320), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_organization_id'), 'email_log', ['organization_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_client_id'), 'companies', ['client_id'], unique=False)
    op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
    op.create_table('conversion_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'platform', name='uq_conversion_config_client_platform')
    )
    op.create_index(op.f('ix_conversion_configs_client_id'), 'conversion_configs', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversion_configs_organization_id'), 'conversion_configs', ['organization_id'], unique=False)
    op.create_table('creatives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('body', sa.String(length=2000), nullable=True),
    sa.Column('media_type', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1000), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_creative_platform_ext')
    )
    op.create_index(op.f('ix_creatives_client_id'), 'creatives', ['client_id'], unique=False)
    op.create_index(op.f('ix_creatives_organization_id'), 'creatives', ['organization_id'], unique=False)
    op.create_table('insights_daily',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_external_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=False),
    sa.Column('clicks', sa.BigInteger(), nullable=False),
    sa.Column('spend_micros', sa.BigInteger(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'entity_type', 'entity_external_id', 'date', name='uq_insight_entity_day')
    )
    op.create_index(op.f('ix_insights_daily_client_id'), 'insights_daily', ['client_id'], unique=False)
    op.create_index(op.f('ix_insights_daily_organization_id'), 'insights_daily', ['organization_id'], unique=False)
    op.create_table('lead_form_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_key', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_key', name='uq_lead_form_platform_key')
    )
    op.create_index(op.f('ix_lead_form_configs_client_id'), 'lead_form_configs', ['client_id'], unique=False)
    op.create_index(op.f('ix_lead_form_configs_external_key'), 'lead_form_configs', ['external_key'], unique=False)
    op.create_index(op.f('ix_lead_form_configs_organization_id'), 'lead_form_configs', ['organization_id'], unique=False)
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_client_id'), 'pipelines', ['client_id'], unique=False)
    op.create_index(op.f('ix_pipelines_organization_id'), 'pipelines', ['organization_id'], unique=False)
    op.create_table('platform_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('external_user_id', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'platform', name='uq_connection_client_platform')
    )
    op.create_index(op.f('ix_platform_connections_organization_id'), 'platform_connections', ['organization_id'], unique=False)
    op.create_table('quality_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_external_id', sa.String(length=150), nullable=False),
    sa.Column('entity_name', sa.String(length=400), nullable=True),
    sa.Column('metric', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('value_label', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'entity_type', 'entity_external_id', 'metric', 'date', name='uq_quality_snapshot')
    )
    op.create_index(op.f('ix_quality_snapshots_client_id'), 'quality_snapshots', ['client_id'], unique=False)
    op.create_index(op.f('ix_quality_snapshots_organization_id'), 'quality_snapshots', ['organization_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_tag_client_name')
    )
    op.create_index(op.f('ix_tags_client_id'), 'tags', ['client_id'], unique=False)
    op.create_index(op.f('ix_tags_organization_id'), 'tags', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('ad_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['connection_id'], ['platform_connections.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_ad_account_platform_ext')
    )
    op.create_index(op.f('ix_ad_accounts_organization_id'), 'ad_accounts', ['organization_id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('feature', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micro_usd', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_organization_id'), 'ai_usage', ['organization_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_external_id', sa.String(length=100), nullable=True),
    sa.Column('source_detail', sa.JSON(), nullable=True),
    sa.Column('qualification', sa.JSON(), nullable=True),
    sa.Column('qualified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_crm_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'source_external_id', name='uq_contact_source_external')
    )
    op.create_index(op.f('ix_contacts_client_id'), 'contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_external_crm_id'), 'contacts', ['external_crm_id'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('widgets', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', name='uq_layout_user_client')
    )
    op.create_index(op.f('ix_dashboard_layouts_organization_id'), 'dashboard_layouts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dashboard_layouts_user_id'), 'dashboard_layouts', ['user_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_qualified_stage', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'position', name='uq_stage_position')
    )
    op.create_index(op.f('ix_pipeline_stages_organization_id'), 'pipeline_stages', ['organization_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('ad_account_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('daily_budget_micros', sa.BigInteger(), nullable=True),
    sa.Column('lifetime_budget_micros', sa.BigInteger(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_campaign_platform_ext')
    )
    op.create_index(op.f('ix_campaigns_client_id'), 'campaigns', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_table('contact_tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'tag_id', name='uq_contact_tag')
    )
    op.create_index(op.f('ix_contact_tags_organization_id'), 'contact_tags', ['organization_id'], unique=False)
    op.create_table('deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('pipeline_id', sa.String(length=36), nullable=False),
    sa.Column('stage_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('value_cents', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deals_client_id'), 'deals', ['client_id'], unique=False)
    op.create_index(op.f('ix_deals_organization_id'), 'deals', ['organization_id'], unique=False)
    op.create_table('landing_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('landing_url', sa.String(length=2000), nullable=True),
    sa.Column('utm_source', sa.String(length=300), nullable=True),
    sa.Column('utm_medium', sa.String(length=300), nullable=True),
    sa.Column('utm_campaign', sa.String(length=300), nullable=True),
    sa.Column('utm_content', sa.String(length=300), nullable=True),
    sa.Column('utm_term', sa.String(length=300), nullable=True),
    sa.Column('referrer', sa.String(length=2000), nullable=True),
    sa.Column('fbclid', sa.String(length=500), nullable=True),
    sa.Column('fbp', sa.String(length=500), nullable=True),
    sa.Column('gclid', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_events_client_id'), 'landing_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_landing_events_contact_id'), 'landing_events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_landing_events_organization_id'), 'landing_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_landing_events_session_key'), 'landing_events', ['session_key'], unique=False)
    op.create_table('pending_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('ad_account_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('entity_external_id', sa.String(length=100), nullable=True),
    sa.Column('entity_name', sa.String(length=400), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['executed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_changes_client_id'), 'pending_changes', ['client_id'], unique=False)
    op.create_index(op.f('ix_pending_changes_organization_id'), 'pending_changes', ['organization_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_client_id'), 'activities', ['client_id'], unique=False)
    op.create_index(op.f('ix_activities_organization_id'), 'activities', ['organization_id'], unique=False)
    op.create_table('ad_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_ad_group_platform_ext')
    )
    op.create_index(op.f('ix_ad_groups_client_id'), 'ad_groups', ['client_id'], unique=False)
    op.create_index(op.f('ix_ad_groups_organization_id'), 'ad_groups', ['organization_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('pending_change_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('ad_account_external_id', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_external_id', sa.String(length=100), nullable=True),
    sa.Column('entity_name', sa.String(length=400), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('diff', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['pending_change_id'], ['pending_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_client_id'), 'audit_log', ['client_id'], unique=False)
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_table('conversion_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('landing_event_id', sa.String(length=36), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_source_url', sa.String(length=2000), nullable=True),
    sa.Column('value_cents', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['landing_event_id'], ['landing_events.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_events_client_id'), 'conversion_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_contact_id'), 'conversion_events', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_event_id'), 'conversion_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_conversion_events_organization_id'), 'conversion_events', ['organization_id'], unique=False)
    op.create_table('crm_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('deal_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_tasks_client_id'), 'crm_tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_crm_tasks_organization_id'), 'crm_tasks', ['organization_id'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('ad_group_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('creative_id', sa.String(length=36), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ad_group_id'], ['ad_groups.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['creative_id'], ['creatives.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id', name='uq_ad_platform_ext')
    )
    op.create_index(op.f('ix_ads_client_id'), 'ads', ['client_id'], unique=False)
    op.create_index(op.f('ix_ads_organization_id'), 'ads', ['organization_id'], unique=False)
    op.create_table('conversion_dispatches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('conversion_event_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('match_keys', sa.JSON(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['conversion_event_id'], ['conversion_events.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_dispatches_client_id'), 'conversion_dispatches', ['client_id'], unique=False)
    op.create_index(op.f('ix_conversion_dispatches_conversion_event_id'), 'conversion_dispatches', ['conversion_event_id'], unique=False)
    op.create_index(op.f('ix_conversion_dispatches_organization_id'), 'conversion_dispatches', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversion_dispatches_organization_id'), table_name='conversion_dispatches')
    op.drop_index(op.f('ix_conversion_dispatches_conversion_event_id'), table_name='conversion_dispatches')
    op.drop_index(op.f('ix_conversion_dispatches_client_id'), table_name='conversion_dispatches')
    op.drop_table('conversion_dispatches')
    op.drop_index(op.f('ix_ads_organization_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_client_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_crm_tasks_organization_id'), table_name='crm_tasks')
    op.drop_index(op.f('ix_crm_tasks_client_id'), table_name='crm_tasks')
    op.drop_table('crm_tasks')
    op.drop_index(op.f('ix_conversion_events_organization_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_event_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_contact_id'), table_name='conversion_events')
    op.drop_index(op.f('ix_conversion_events_client_id'), table_name='conversion_events')
    op.drop_table('conversion_events')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_client_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ad_groups_organization_id'), table_name='ad_groups')
    op.drop_index(op.f('ix_ad_groups_client_id'), table_name='ad_groups')
    op.drop_table('ad_groups')
    op.drop_index(op.f('ix_activities_organization_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_client_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_pending_changes_organization_id'), table_name='pending_changes')
    op.drop_index(op.f('ix_pending_changes_client_id'), table_name='pending_changes')
    op.drop_table('pending_changes')
    op.drop_index(op.f('ix_landing_events_session_key'), table_name='landing_events')
    op.drop_index(op.f('ix_landing_events_organization_id'), table_name='landing_events')
    op.drop_index(op.f('ix_landing_events_contact_id'), table_name='landing_events')
    op.drop_index(op.f('ix_landing_events_client_id'), table_name='landing_events')
    op.drop_table('landing_events')
    op.drop_index(op.f('ix_deals_organization_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_client_id'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_contact_tags_organization_id'), table_name='contact_tags')
    op.drop_table('contact_tags')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_client_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_pipeline_stages_organization_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_dashboard_layouts_user_id'), table_name='dashboard_layouts')
    op.drop_index(op.f('ix_dashboard_layouts_organization_id'), table_name='dashboard_layouts')
    op.drop_table('dashboard_layouts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_external_crm_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_client_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_ai_usage_organization_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_ad_accounts_organization_id'), table_name='ad_accounts')
    op.drop_table('ad_accounts')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_organization_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_client_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_quality_snapshots_organization_id'), table_name='quality_snapshots')
    op.drop_index(op.f('ix_quality_snapshots_client_id'), table_name='quality_snapshots')
    op.drop_table('quality_snapshots')
    op.drop_index(op.f('ix_platform_connections_organization_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_pipelines_organization_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_client_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_lead_form_configs_organization_id'), table_name='lead_form_configs')
    op.drop_index(op.f('ix_lead_form_configs_external_key'), table_name='lead_form_configs')
    op.drop_index(op.f('ix_lead_form_configs_client_id'), table_name='lead_form_configs')
    op.drop_table('lead_form_configs')
    op.drop_index(op.f('ix_insights_daily_organization_id'), table_name='insights_daily')
    op.drop_index(op.f('ix_insights_daily_client_id'), table_name='insights_daily')
    op.drop_table('insights_daily')
    op.drop_index(op.f('ix_creatives_organization_id'), table_name='creatives')
    op.drop_index(op.f('ix_creatives_client_id'), table_name='creatives')
    op.drop_table('creatives')
    op.drop_index(op.f('ix_conversion_configs_organization_id'), table_name='conversion_configs')
    op.drop_index(op.f('ix_conversion_configs_client_id'), table_name='conversion_configs')
    op.drop_table('conversion_configs')
    op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_client_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_email_log_organization_id'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_clients_vertical'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_organizations_custom_domain'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
