"""org stripe billing columns

Revision ID: 71c302e70828
Revises: 31054845db94
Create Date: 2026-07-08 02:30:37.013554
"""
from alembic import op
import sqlalchemy as sa


revision = '71c302e70828'
down_revision = '31054845db94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=64), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_organizations_stripe_customer_id'), 'organizations', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_stripe_customer_id'), table_name='organizations')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###
