"""user email_verified

Revision ID: 8f3bbc3e1487
Revises: 71c302e70828
Create Date: 2026-07-08 02:35:41.647102
"""
from alembic import op
import sqlalchemy as sa


revision = '8f3bbc3e1487'
down_revision = '71c302e70828'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default lets this apply cleanly to a table that already has rows
    # (existing users default to unverified).
    op.add_column(
        'users',
        sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
