"""teams, invites & memberships (Phase 13)

Revision ID: a1329e8b7c04
Revises: e522d55c44a7
Create Date: 2026-07-10

Creates the multi-org membership table (backfilled from existing team-role
users so every current user keeps exactly the access they had), the invites
table, and the membership audit log.
"""
import uuid

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1329e8b7c04"
down_revision = "e522d55c44a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "user_id", name="uq_membership_org_user"),
    )
    op.create_index(
        op.f("ix_organization_memberships_organization_id"),
        "organization_memberships",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_memberships_user_id"),
        "organization_memberships",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "organization_invites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("invited_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["accepted_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["invited_by_user_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_invites_email"),
        "organization_invites",
        ["email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_invites_organization_id"),
        "organization_invites",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organization_invites_token_hash"),
        "organization_invites",
        ["token_hash"],
        unique=True,
    )
    op.create_table(
        "membership_audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=False),
        sa.Column("actor_email", sa.String(length=320), nullable=False),
        sa.Column("actor_name", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("target_user_id", sa.String(length=36), nullable=True),
        sa.Column("target_email", sa.String(length=320), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_membership_audit_log_organization_id"),
        "membership_audit_log",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Backfill: one membership per existing team-role user, mirroring the
    # single-org world exactly. Client portal users get no membership rows
    # (they stay pinned to the User row's organization_id/client_id).
    bind = op.get_bind()
    users = sa.table(
        "users",
        sa.column("id", sa.String),
        sa.column("organization_id", sa.String),
        sa.column("role", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    memberships = sa.table(
        "organization_memberships",
        sa.column("id", sa.String),
        sa.column("organization_id", sa.String),
        sa.column("user_id", sa.String),
        sa.column("role", sa.String),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    rows = bind.execute(
        sa.select(users.c.id, users.c.organization_id, users.c.role, users.c.created_at)
        .where(users.c.role.in_(["owner", "admin", "member"]))
    ).fetchall()
    if rows:
        bind.execute(
            memberships.insert(),
            [
                {
                    "id": str(uuid.uuid4()),
                    "organization_id": r.organization_id,
                    "user_id": r.id,
                    "role": r.role,
                    "created_at": r.created_at,
                }
                for r in rows
            ],
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_membership_audit_log_organization_id"), table_name="membership_audit_log"
    )
    op.drop_table("membership_audit_log")
    op.drop_index(
        op.f("ix_organization_invites_token_hash"), table_name="organization_invites"
    )
    op.drop_index(
        op.f("ix_organization_invites_organization_id"), table_name="organization_invites"
    )
    op.drop_index(op.f("ix_organization_invites_email"), table_name="organization_invites")
    op.drop_table("organization_invites")
    op.drop_index(
        op.f("ix_organization_memberships_user_id"), table_name="organization_memberships"
    )
    op.drop_index(
        op.f("ix_organization_memberships_organization_id"),
        table_name="organization_memberships",
    )
    op.drop_table("organization_memberships")
    # ### end Alembic commands ###
