"""integration_credentials

Revision ID: b9b625ffb744
Revises: 8f3bbc3e1487
Create Date: 2026-07-08 12:57:06.163992
"""
from alembic import op
import sqlalchemy as sa


revision = 'b9b625ffb744'
down_revision = '8f3bbc3e1487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('public_id', sa.String(length=128), nullable=True),
    sa.Column('login_customer_id', sa.String(length=32), nullable=True),
    sa.Column('secret_encrypted', sa.Text(), nullable=True),
    sa.Column('secret2_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'provider', name='uq_integration_org_provider')
    )
    op.create_index(op.f('ix_integration_credentials_organization_id'), 'integration_credentials', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_credentials_organization_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    # ### end Alembic commands ###
