"""outreach module

Revision ID: e522d55c44a7
Revises: f2b6d90c4a17
Create Date: 2026-07-10 01:10:42.786719
"""
from alembic import op
import sqlalchemy as sa


revision = 'e522d55c44a7'
down_revision = 'f2b6d90c4a17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('daily_send_cap', sa.Integer(), nullable=False),
    sa.Column('automation_paused', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_user_id', name='uq_ig_account_user')
    )
    op.create_index(op.f('ix_instagram_accounts_client_id'), 'instagram_accounts', ['client_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_ig_user_id'), 'instagram_accounts', ['ig_user_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_organization_id'), 'instagram_accounts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_page_id'), 'instagram_accounts', ['page_id'], unique=False)
    op.create_table('instagram_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_ig_event_account_ext')
    )
    op.create_index(op.f('ix_instagram_webhook_events_account_id'), 'instagram_webhook_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_instagram_webhook_events_client_id'), 'instagram_webhook_events', ['client_id'], unique=False)
    op.create_index(op.f('ix_instagram_webhook_events_organization_id'), 'instagram_webhook_events', ['organization_id'], unique=False)
    op.create_table('outreach_sequences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_first_day', sa.Boolean(), nullable=False),
    sa.Column('exit_on_reply', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_sequences_account_id'), 'outreach_sequences', ['account_id'], unique=False)
    op.create_index(op.f('ix_outreach_sequences_client_id'), 'outreach_sequences', ['client_id'], unique=False)
    op.create_index(op.f('ix_outreach_sequences_organization_id'), 'outreach_sequences', ['organization_id'], unique=False)
    op.create_table('outreach_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('peer', sa.JSON(), nullable=True),
    sa.Column('last_user_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.String(length=400), nullable=True),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ig_user_id', name='uq_convo_account_user')
    )
    op.create_index(op.f('ix_outreach_conversations_account_id'), 'outreach_conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_outreach_conversations_client_id'), 'outreach_conversations', ['client_id'], unique=False)
    op.create_index(op.f('ix_outreach_conversations_contact_id'), 'outreach_conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outreach_conversations_ig_user_id'), 'outreach_conversations', ['ig_user_id'], unique=False)
    op.create_index(op.f('ix_outreach_conversations_last_message_at'), 'outreach_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_outreach_conversations_organization_id'), 'outreach_conversations', ['organization_id'], unique=False)
    op.create_table('outreach_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text_a', sa.Text(), nullable=True),
    sa.Column('text_b', sa.Text(), nullable=True),
    sa.Column('promoted_variant', sa.String(length=1), nullable=True),
    sa.Column('wait_hours', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('on_true', sa.String(length=20), nullable=True),
    sa.Column('on_false', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['outreach_sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'position', name='uq_step_position')
    )
    op.create_index(op.f('ix_outreach_steps_organization_id'), 'outreach_steps', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_steps_sequence_id'), 'outreach_steps', ['sequence_id'], unique=False)
    op.create_table('outreach_trigger_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('media_ids', sa.JSON(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=True),
    sa.Column('create_contact', sa.Boolean(), nullable=False),
    sa.Column('tag_names', sa.JSON(), nullable=True),
    sa.Column('enroll_sequence_id', sa.String(length=36), nullable=True),
    sa.Column('capture_prospect', sa.Boolean(), nullable=False),
    sa.Column('once_per_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['enroll_sequence_id'], ['outreach_sequences.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_trigger_rules_account_id'), 'outreach_trigger_rules', ['account_id'], unique=False)
    op.create_index(op.f('ix_outreach_trigger_rules_client_id'), 'outreach_trigger_rules', ['client_id'], unique=False)
    op.create_index(op.f('ix_outreach_trigger_rules_organization_id'), 'outreach_trigger_rules', ['organization_id'], unique=False)
    op.create_table('outreach_prospects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('ig_user_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vertical', sa.String(length=100), nullable=True),
    sa.Column('enrichment', sa.JSON(), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('sequence_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['instagram_accounts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['outreach_conversations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['outreach_sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'username', name='uq_prospect_client_username')
    )
    op.create_index(op.f('ix_outreach_prospects_account_id'), 'outreach_prospects', ['account_id'], unique=False)
    op.create_index(op.f('ix_outreach_prospects_client_id'), 'outreach_prospects', ['client_id'], unique=False)
    op.create_index(op.f('ix_outreach_prospects_ig_user_id'), 'outreach_prospects', ['ig_user_id'], unique=False)
    op.create_index(op.f('ix_outreach_prospects_organization_id'), 'outreach_prospects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_prospects_vertical'), 'outreach_prospects', ['vertical'], unique=False)
    op.create_table('outreach_enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('prospect_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('waiting_window', sa.Boolean(), nullable=False),
    sa.Column('variant_assignments', sa.JSON(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enrolled_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['outreach_conversations.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['prospect_id'], ['outreach_prospects.id'], ),
    sa.ForeignKeyConstraint(['sequence_id'], ['outreach_sequences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'conversation_id', name='uq_enroll_seq_convo')
    )
    op.create_index(op.f('ix_outreach_enrollments_client_id'), 'outreach_enrollments', ['client_id'], unique=False)
    op.create_index(op.f('ix_outreach_enrollments_conversation_id'), 'outreach_enrollments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_outreach_enrollments_next_run_at'), 'outreach_enrollments', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_outreach_enrollments_organization_id'), 'outreach_enrollments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_enrollments_sequence_id'), 'outreach_enrollments', ['sequence_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.String(length=5), nullable=False),
    sa.Column('external_mid', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('enrollment_id', sa.String(length=36), nullable=True),
    sa.Column('step_id', sa.String(length=36), nullable=True),
    sa.Column('variant', sa.String(length=1), nullable=True),
    sa.Column('replied_to', sa.Boolean(), nullable=False),
    sa.Column('message_tag', sa.String(length=30), nullable=True),
    sa.Column('sent_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reply_to_comment_id', sa.String(length=100), nullable=True),
    sa.Column('api_response', sa.JSON(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['outreach_conversations.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['outreach_enrollments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['outreach_trigger_rules.id'], ),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['outreach_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'external_mid', name='uq_msg_convo_mid')
    )
    op.create_index(op.f('ix_outreach_messages_client_id'), 'outreach_messages', ['client_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_conversation_id'), 'outreach_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_organization_id'), 'outreach_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outreach_messages_sent_at'), 'outreach_messages', ['sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_messages_sent_at'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_organization_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_conversation_id'), table_name='outreach_messages')
    op.drop_index(op.f('ix_outreach_messages_client_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_outreach_enrollments_sequence_id'), table_name='outreach_enrollments')
    op.drop_index(op.f('ix_outreach_enrollments_organization_id'), table_name='outreach_enrollments')
    op.drop_index(op.f('ix_outreach_enrollments_next_run_at'), table_name='outreach_enrollments')
    op.drop_index(op.f('ix_outreach_enrollments_conversation_id'), table_name='outreach_enrollments')
    op.drop_index(op.f('ix_outreach_enrollments_client_id'), table_name='outreach_enrollments')
    op.drop_table('outreach_enrollments')
    op.drop_index(op.f('ix_outreach_prospects_vertical'), table_name='outreach_prospects')
    op.drop_index(op.f('ix_outreach_prospects_organization_id'), table_name='outreach_prospects')
    op.drop_index(op.f('ix_outreach_prospects_ig_user_id'), table_name='outreach_prospects')
    op.drop_index(op.f('ix_outreach_prospects_client_id'), table_name='outreach_prospects')
    op.drop_index(op.f('ix_outreach_prospects_account_id'), table_name='outreach_prospects')
    op.drop_table('outreach_prospects')
    op.drop_index(op.f('ix_outreach_trigger_rules_organization_id'), table_name='outreach_trigger_rules')
    op.drop_index(op.f('ix_outreach_trigger_rules_client_id'), table_name='outreach_trigger_rules')
    op.drop_index(op.f('ix_outreach_trigger_rules_account_id'), table_name='outreach_trigger_rules')
    op.drop_table('outreach_trigger_rules')
    op.drop_index(op.f('ix_outreach_steps_sequence_id'), table_name='outreach_steps')
    op.drop_index(op.f('ix_outreach_steps_organization_id'), table_name='outreach_steps')
    op.drop_table('outreach_steps')
    op.drop_index(op.f('ix_outreach_conversations_organization_id'), table_name='outreach_conversations')
    op.drop_index(op.f('ix_outreach_conversations_last_message_at'), table_name='outreach_conversations')
    op.drop_index(op.f('ix_outreach_conversations_ig_user_id'), table_name='outreach_conversations')
    op.drop_index(op.f('ix_outreach_conversations_contact_id'), table_name='outreach_conversations')
    op.drop_index(op.f('ix_outreach_conversations_client_id'), table_name='outreach_conversations')
    op.drop_index(op.f('ix_outreach_conversations_account_id'), table_name='outreach_conversations')
    op.drop_table('outreach_conversations')
    op.drop_index(op.f('ix_outreach_sequences_organization_id'), table_name='outreach_sequences')
    op.drop_index(op.f('ix_outreach_sequences_client_id'), table_name='outreach_sequences')
    op.drop_index(op.f('ix_outreach_sequences_account_id'), table_name='outreach_sequences')
    op.drop_table('outreach_sequences')
    op.drop_index(op.f('ix_instagram_webhook_events_organization_id'), table_name='instagram_webhook_events')
    op.drop_index(op.f('ix_instagram_webhook_events_client_id'), table_name='instagram_webhook_events')
    op.drop_index(op.f('ix_instagram_webhook_events_account_id'), table_name='instagram_webhook_events')
    op.drop_table('instagram_webhook_events')
    op.drop_index(op.f('ix_instagram_accounts_page_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_organization_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_ig_user_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_client_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    # ### end Alembic commands ###
